### ISSUE TITLE
Error [gulp-premailer] spawn ENOENT

### ISSUE THREAD

**Issue by daphnesmit** [justin713/gulp-premailer#9]
I am getting a 'Error [gulp-premailer] spawn ENOENT' when running it on a html file.

```
Error [gulp-premailer] spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
Error stream.push() after EOF
    at readableAddChunk (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:168:15)
    at Transform.Readable.push (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at Transform.push (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at ChildProcess.<anonymous> (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/index.js:115:9)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
Error no writecb in Transform class
    at afterTransform (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at ChildProcess.<anonymous> (/Users/daphnes/Sites/timing/email/node_modules/gulp-premailer/index.js:116:4)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by rodrigoreal** [comment]
I'm also getting this error, did you found a solution?
